In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
dataset=load_diabetes()

In [3]:
x=dataset.data
y=dataset.target

In [4]:
lr=LinearRegression()

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=42)

In [6]:
lr.fit(x_train,y_train)

LinearRegression()

In [34]:
y_pred=lr.predict(x_test)
y_pred

array([136.98656074, 181.28774532, 131.3963031 , 276.84252558,
       119.99199925,  91.81458389, 261.50440322, 182.1471634 ,
        81.08264568, 112.80189841,  95.19269682, 158.41940907,
        60.77434209, 201.2503426 ,  97.10996264, 132.17230855,
       214.84929359, 245.43663419, 198.89785779, 215.2080922 ,
       204.03105624,  85.83842218,  68.80784003, 186.95400879,
       159.31666784, 161.26892978, 192.46231791, 175.43315525,
        48.26170883, 109.02440887, 178.78735199,  89.26131753,
       130.34030205, 177.49825562, 168.73498375, 196.59149332,
       120.26617836, 115.26096142, 139.41091391,  57.65781289,
        69.32516364, 107.47995394, 161.49582752, 141.46854024,
       163.43731666,  64.44345728,  74.98923905, 106.29426822,
        53.20428955, 161.94050913, 158.40167496,  64.70634012,
       107.2493344 , 105.79759552, 169.33266183, 162.82449457,
        91.40910837, 209.52006744, 119.1445184 ,  68.5183609 ,
       182.77973408, 202.65229325, 145.09032702, 104.83

In [8]:
r2_score(y_test,y_pred)

0.5157436313902429

In [9]:
lr.coef_

array([  18.08799763, -227.04344876,  592.27723487,  361.54123241,
       -655.90738774,  353.71636413,   14.41265469,  142.87369371,
        594.01542882,   31.67317969])

In [10]:
lr.intercept_

148.92850837170067

In [31]:
class MeraMLR:
    def __init__(self):
        self.coef_=None
        self.intercept_=None

    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        self.intercept_=betas[0]
        self.coef_=betas[1:]

    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_)+self.intercept_
        return y_pred

In [32]:
obj=MeraMLR()
obj.fit(x_train,y_train)

In [33]:
obj.predict(x_test)

array([136.98656074, 181.28774532, 131.3963031 , 276.84252558,
       119.99199925,  91.81458389, 261.50440322, 182.1471634 ,
        81.08264568, 112.80189841,  95.19269682, 158.41940907,
        60.77434209, 201.2503426 ,  97.10996264, 132.17230855,
       214.84929359, 245.43663419, 198.89785779, 215.2080922 ,
       204.03105624,  85.83842218,  68.80784003, 186.95400879,
       159.31666784, 161.26892978, 192.46231791, 175.43315525,
        48.26170883, 109.02440887, 178.78735199,  89.26131753,
       130.34030205, 177.49825562, 168.73498375, 196.59149332,
       120.26617836, 115.26096142, 139.41091391,  57.65781289,
        69.32516364, 107.47995394, 161.49582752, 141.46854024,
       163.43731666,  64.44345728,  74.98923905, 106.29426822,
        53.20428955, 161.94050913, 158.40167496,  64.70634012,
       107.2493344 , 105.79759552, 169.33266183, 162.82449457,
        91.40910837, 209.52006744, 119.1445184 ,  68.5183609 ,
       182.77973408, 202.65229325, 145.09032702, 104.83

In [35]:
r2_score(y_test,y_pred)

0.5157436313902429

In [36]:
print(obj.coef_)
print(obj.intercept_)

[  18.08799763 -227.04344876  592.27723487  361.54123241 -655.90738774
  353.71636413   14.41265469  142.87369371  594.01542882   31.67317969]
148.92850837170067
